//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquidDynamics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiquidDynamics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр {0} должен быть числом с плавающей точкой..
        /// </summary>
        internal static string Analytical_Barotropic_ParameterMustBeDouble {
            get {
                return ResourceManager.GetString("Analytical_Barotropic_ParameterMustBeDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр {0} должен быть целым числом..
        /// </summary>
        internal static string Analytical_Barotropic_ParameterMustBeInteger {
            get {
                return ResourceManager.GetString("Analytical_Barotropic_ParameterMustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр {0} должен быть больше 1..
        /// </summary>
        internal static string Analytical_Barotrpic_ParameterMustBeGreaterThanOne {
            get {
                return ResourceManager.GetString("Analytical_Barotrpic_ParameterMustBeGreaterThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр {0} должен быть больше 0..
        /// </summary>
        internal static string Analytical_Barotrpic_ParameterMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Analytical_Barotrpic_ParameterMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестовая задача.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры графиков.
        /// </summary>
        internal static string GraphParameters {
            get {
                return ResourceManager.GetString("GraphParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное значение.
        /// </summary>
        internal static string IncorrectValue {
            get {
                return ResourceManager.GetString("IncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное значение. Значение параметра должно быть в диапазоне [{0}, {1}]..
        /// </summary>
        internal static string InvalidCutValue {
            get {
                return ResourceManager.GetString("InvalidCutValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное значение параметра {0}..
        /// </summary>
        internal static string InvalidParameterValue {
            get {
                return ResourceManager.GetString("InvalidParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное значение параметра {0}. Значение параметра должно лежать в диапазоне [{1}, {2}]..
        /// </summary>
        internal static string InvalidParameterValueBoundsBroken {
            get {
                return ResourceManager.GetString("InvalidParameterValueBoundsBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное значение параметра Z. Значение параметра должно лежать в диапазоне ({0}, {1})..
        /// </summary>
        internal static string InvalidUpwellingParameterValue {
            get {
                return ResourceManager.GetString("InvalidUpwellingParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IssykKulData {
            get {
                object obj = ResourceManager.GetObject("IssykKulData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IssykKulGraphData {
            get {
                object obj = ResourceManager.GetObject("IssykKulGraphData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minus {
            get {
                object obj = ResourceManager.GetObject("Minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plus {
            get {
                object obj = ResourceManager.GetObject("Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры задачи.
        /// </summary>
        internal static string ProblemParameters {
            get {
                return ResourceManager.GetString("ProblemParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Start {
            get {
                object obj = ResourceManager.GetObject("Start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StepBackward {
            get {
                object obj = ResourceManager.GetObject("StepBackward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StepForward {
            get {
                object obj = ResourceManager.GetObject("StepForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле скоростей: (u, v).
        /// </summary>
        internal static string UVSquareVelocityField {
            get {
                return ResourceManager.GetString("UVSquareVelocityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле скоростей: (u, w).
        /// </summary>
        internal static string UWSquareVelocityField {
            get {
                return ResourceManager.GetString("UWSquareVelocityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле скоростей: (v, w).
        /// </summary>
        internal static string VWSquareVelocityField {
            get {
                return ResourceManager.GetString("VWSquareVelocityField", resourceCulture);
            }
        }
    }
}
